name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository kodi
        uses: actions/checkout@v4

      - name: AWS Serverga SSH orqali ulanish va Yangilash
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_SERVER_IP }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          script: |
            cd /home/ec2-user
            
            # Agar eski noto'g'ri nomlangan papka bo'lsa o'chirib tashlaymiz
            rm -rf Wedding
            
            # Kichik harf bilan yangitdan toza clone qilamiz
            if [ ! -d "wedding" ]; then
              git clone https://github.com/gavharoy06/Wedding.git wedding
            fi
            
            # DIQQAT: Agar papkangiz nomi 'bachend' bo'lsa, pastdagi backend so'zini bachend qiling:
            cd /home/ec2-user/wedding/backend
            
            git reset --hard HEAD
            git pull origin main
            
            npm install
            npm run build
            
            pm2 restart wedding-backend || pm2 start dist/server.js --name "wedding-backend"